name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - name: Run clone Setup
        run: git clone https://silica.codes/Li/NoPssDrm.git -b no-root input
      - name: Prepare environment
        run: |
          sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
          sudo apt update
      - name: Setup Depencies
        run: sudo apt install openjdk-8-jdk diffutils patch wget bspatch zipalign -y
      - name: Get next version code
        id: next_ver_code
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=$(gh release list -L 1 | awk -F '\t' '{print $3}')
          if [ -z "$TAG" ]; then TAG=0; fi
          echo "NEXT_VER_CODE=$((TAG + 1))" >> $GITHUB_OUTPUT
      - name: Run Build
        run: bash input/build_patched_apk.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: $GITHUB_REPOSITORY
          NEXT_VER_CODE: ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
      - name: Release NOPSSDRM
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./input/PSM_NoPsmDrm_NoRoot.apk
          tag: ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
          overwrite: true
          body: "NoPsmDrm Apk"
          file_glob: true
